version = 0.1

[dev.deploy.parameters]
stack_name = "answernow-backend-dev"
resolve_s3 = true
s3_prefix = "answernow-backend-dev"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[dev.global.parameters]
region = "us-west-2"
